spring:
  application:
    name: AUTH-SERVICE

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /grocery-documentation
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /grocery-api-docs

rental:
  openapi:
    dev-url: http://localhost:9090
    prod-url: https://grocery-api.com