spring:
  application:
    name: GROCERY-API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/categories/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
